# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code,
# publish them to NPM registry and publish their release notes to Github

name: Node.js CI Publish packages

permission:
  contents: write


on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --immutable
      - run: yarn build
      - name: Run publish script
        run: node bin/publish.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


